name: Deploy Gatsby to Firebase

on:
  push:
    branches:
      - main  # Change this if your main branch is named differently

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Use Node.js version 20 (same as local)

      - name: Install Firebase Tools
        run: npm install -g firebase-tools  # Ensure Firebase tools are installed

      - name: Install Dependencies
        run: npm install  # Or yarn install if using Yarn

      - name: Build Gatsby
        run: npm run build  # Or yarn build

      - name: Check Firebase Tools Version
        run: firebase --version  # Verify if Firebase CLI is installed

      - name: Verify Firebase Token
        run: echo ${{ secrets.FIREBASE_TOKEN }}  # Check token format

      - name: Firebase Login Using Token
        run: echo "$FIREBASE_TOKEN" | firebase login:ci --token  # Explicit login with token

      - name: Select Firebase Project
        run: firebase use --token "$FIREBASE_TOKEN"  # Ensure the correct Firebase project is selected

      - name: Deploy to Firebase
        run: |
          firebase deploy --token "$FIREBASE_TOKEN"
